from . import hr_contract_type
from . import categorie_salariale
from . import echelon_salariale
from . import grille_salaire
from . import hr_contract
from . import prime_ret
from . import hr_payslip
from . import payslip_primes
from . import avancement
from . import res_company
from . import hr_payslip_run
from . import hr_salary_rule
from . import categorie_bulletin
